README.md
* Adjust the terminology (host ABI vs. client SDK)
* Avoid "_identical_ to those running on Envoy" terminology (to make it clear we're not aiming for bug-for-bug compatibility)
* Mention it's a format adopted by multiple gateways, including Kong
=> docs(readme) clarify proxy-wasm section

util/release.sh, util/runtime.sh
Attempt at speeding up the release build pipeline as much as possible.
=> chore(release) only build V8 of all runtimes during binary build

Makefile
"CI Large" once re-enabled will help covering other OpenSSL versions if needed.
=> chore(deps) bump OpenSSL to 3.1.2

util/runtimes/v8.sh
With existing clones being updated, gclient sometimes complain that existing dependencies have been removed, and that we should run with `-D`. Since this is not a development environment, let's always run with `-D`.
See: https://chromium.googlesource.com/chromium/tools/depot_tools.git/+/08e2e0cc9dc3404f1905a2f2741a8553c86d6f77/gclient.py#3092
=> chore(util/v8) use 'gclient sync -D'

src/wasm/wrt/ngx_wrt_wasmtime.c, t/01-wasm/directives/006-backtraces_directive.t, t/TestWasm.pm
With `backtraces on`, `WASMTIME_BACKTRACE_DETAILS` is forcefully enabled.
With `backtraces off` (default), `WASMTIME_BACKTRACE_DETAILS` still defaults to `0` but can be overridden if specified in the `env` directive.
This commit also ensures the `env` directives in `TestWasm.pm` are actually injected, although it disables the injection since no environment variable is presently injected.
=> fix(wrt/wasmtime) do not override 'WASMTIME_BACKTRACE_DETAILS' if specified

auto/cargo, config, docs/INSTALL.md, t/10-build/004-ngx_wasm_rs_linking.t, t/TestBuild.pm, util/_lib.sh
First this fixes the test cases and documentation as they were merged, which wrongly assumed `NGX_CC_OPT` and `NGX_LD_OPT` were digested by Nginx's `auto` scripts, they are not. They are derived from `--with-{cc,ld}-opt` arguments.
Second, it moves defines and mandatory checks to `config` since we need both even when `NGX_WASM_CARGO=0` and `auto/cargo` does not run.
The above fixes `NGX_WASM_CARGO=0` as a mean to *completely* disable ngx-wasm-rs, as supported by Wasmer. This "mandatory={yes,no}" behavior is tested for both Wasmer and V8 as well.
Finally, we also consider `NGX_WASM_CARGO` in the local development environment freshness build script.
=> hotfix(config) fix external ngx-wasm-rs builds

lib/ngx-wasm-rs/lib/backtrace/src/c_api.rs, lib/ngx-wasm-rs/lib/backtrace/src/lib.rs, lib/ngx-wasm-rs/lib/wat/src/lib.rs, rust-toolchain, util/test.sh
Implementation based on the Rust standard library implementation for `vec_into_raw_parts`.
See examples from: https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#538-546
Implementation in: https://doc.rust-lang.org/src/alloc/vec/mod.rs.html#818-822
With this change the Rust library now compiles cleanly with stable Rust 1.71.1.
This makes building under a production setup easier as Rust nightly can not be easily pinned and might introduce breaking changes without notice.
Helps unblock: https://github.com/Kong/ngx_wasm_module/pull/392
=> refactor(lib): make Rust module compile-able under stable Rust

.github/workflows/ci-large.yml, .github/workflows/ci.yml, .github/workflows/job-build-tests.yml, .github/workflows/job-unit-tests.yml, assets/release/Dockerfiles/Dockerfile.ubuntu-22.04, src/wasm/ngx_wasm_ops.c, src/wasm/wrt/ngx_wrt_v8.c, src/wasm/wrt/ngx_wrt_wasmer.c, util/_lib.sh
Dockerfiles and CI workflow use the latest version available in the runner OS.
Older versions of gcc and clang are tested in CI Large.
=> chore(ci) bump and sync CC version among Dockerfiles and CI workflows

.github/workflows/job-clang-analyzer.yml, .github/workflows/job-unit-tests.yml, codecov.yml, t/04-openresty/lua-bridge/003-proxy_wasm_lua_resolver_timeouts.t
Codecov has a couple features that Coveralls lacks: better PR comments and PR diff comments of uncovered lines. It's also easier to maintain compared to the `carryforward` flags of Coveralls.
=> chore(ci) restore Codecov support alongside Coveralls

codecov.yml
So PRs checks stay green as much as possible:
* Lower range to 75/90.
* Lower target since many patches may not have 90% coverage.
* Increase drop threshold
=> chore(codecov) update some configuration settings

assets/release/Dockerfiles/Dockerfile.ubuntu-22.04
In the commit 1a0759b22545461431b8de288545e624735cb02f, the Dockerfile used to build the ubuntu 22.04 release image was changed to install `clang-15` instead of `clang` -- applying the intended bump.
It lacked, however, an `update-alternative` call making `clang` available as a link to `clang-15`.
=> chore(ci) fix ubuntu 22.04 release docker image

src/common/proxy_wasm/ngx_proxy_wasm.c, t/04-openresty/ffi/302-proxy_wasm_set_property_host.t
When calling `proxy_wasm.set_property` from Lua, we want a `pwctx` to be able to store a property. But we need to do that before `proxy_wasm.start`, so `pwctx->ready` didn't have a chance to get initialized yet.
Passing `NULL, 0` to `filter_ids` and `nfilters` when obtaining the `pwctx` from the `set_property` FFI call caused the `pwctx` to get initialized with an empty filter list, defeating the configuration previously set up by `proxy_wasm.attach`.
In this fix, we make the `NULL` value of `filter_ids` to mean "please don't do the `pwctx->ready` initialization". The other use of `ngx_proxy_wasm_ctx` in `ngx_wasm_ops.c` always passes a non-NULL value (even when the filter list is empty), because the `elts` pointer is allocated on `ngx_array_init`.
This issue caused an integration failure …
=> fix(proxy-wasm) do not accidentally reset filter list from FFI call

util/test.sh
The servroot should only be cleaned when we are sure it will be overwritten anyway. This allows observing its contents for debugging purposes while running randomized test on the whole suite.
=> chore(util) do not remove test servroot with TEST_NGINX_RANDOMIZE=1

.github/workflows/release.yml
Fixes V8 build which relies on `pkg_resources` -- provided by `setuptools`.
=> chore(release) make sure setuptools is installed on macOS

src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm.h, src/common/proxy_wasm/ngx_proxy_wasm_host.c, src/common/proxy_wasm/ngx_proxy_wasm_properties.c, src/common/proxy_wasm/ngx_proxy_wasm_util.c, src/http/ngx_http_wasm_module.c, src/http/ngx_http_wasm_util.c, src/http/proxy_wasm/ngx_http_proxy_wasm.h, src/http/proxy_wasm/ngx_http_proxy_wasm_dispatch.c, src/wasm/vm/ngx_wavm.c, t/03-proxy_wasm/003-on_tick.t, t/03-proxy_wasm/007-on_http_instance_isolation.t, t/03-proxy_wasm/hfuncs/114-proxy_set_http_request_body.t, t/03-proxy_wasm/hfuncs/119-proxy_properties_get_ngx.t, t/03-proxy_wasm/hfuncs/120-proxy_properties_get_host.t, t/03-proxy_wasm/hfuncs/122-proxy_properties_set_host.t, t/03-proxy_wasm/hfuncs/123-proxy_properties_set_ngx.t, t/04-openresty/ffi/103-proxy_wasm_attach.t, t/lib/proxy-wasm-tests/on-phases/src/filter.rs
* Allow for recycling the root instance (which is not managed by isolation modes).
* Allow for smoother recycling of http instances (including when the root instance has trapped, e.g. during `on_tick`).
* Also recycle trapped instances in the busy queue.
* Less verbose context creation of fresh and/or recycled instances starting in atypical steps (e.g. `on_response_headers`).
* Sweep trapped instances sooner (during runtime instead of worker shutdown).
* Greatly simplify `on_context_create` supporting code and unifies it between root and http instances which now both use the same context creation code. This makes instance recycling much more robust in a number of tricky situations with low isolation modes.
=> refactor(proxy-wasm) better instance/ctx lifecycle management

src/common/proxy_wasm/ngx_proxy_wasm_maps.c
Use the pwexec pool (which is per-request in lower isolation modes) rather than the persistent instance pool in ngx_proxy_wasm_maps_set.
This fixes a memory-hoarding issue observed when filters set headers on every request.
=> fix(proxy-wasm) use pwexec pool in ngx_proxy_wasm_maps_set

.github/workflows/ci-large.yml
[This](https://github.com/Kong/ngx_wasm_module/actions/runs/7160665577) successful run demonstrates the fix.
=> chore(ci) fix large CI workflow file

.github/workflows/ci-large.yml
GitHub seems to complain about a `ci-large.yml:codeql` job not existing.
=> chore(ci) rename 'codeql' job in large CI workflow

t/03-proxy_wasm/007-on_http_instance_isolation.t, t/03-proxy_wasm/hfuncs/120-proxy_properties_get_host.t, t/03-proxy_wasm/hfuncs/123-proxy_properties_set_host.t
Different compilers load the hostcalls filter faster or slower by an order of magnitude (30ms vs 300ms), and cause the old worker "free instance" log to happen sooner or later in req0, especially now that we update the time at module loading.
=> chore(tests) fix test cases for Wasmer in HUP mode

.github/workflows/ci.yml, util/release.sh
Prior:
/assets/release/INSTALL
Now:
/INSTALL
=> chore(release) put 'INSTALL' file at root of source release archives

util/sdks/assemblyscript.sh, util/sdks/go.sh
This prevents `./util/test.sh` from failing when `./util/sdks/go.sh` or`./util/sdks/assemblyscript.sh` attempt to install example filters when the respective SDK hasn't been downloaded (`tinygo` or `npm` not available).
=> chore(util/sdks) check if SDK examples exist before installing them

.github/actions/codeql-config.yml, .github/workflows/job-codeql-analyzer.yml
According to the GHA warning:
> The "paths"/"paths-ignore" fields of the config only have effect
for JavaScript, Python, and Ruby.
=> chore(ci) drop codeql paths/paths-ignore from its config

src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm_host.c, src/http/ngx_http_wasm.h, src/http/ngx_http_wasm_filter_module.c, src/http/ngx_http_wasm_local_response.c, src/http/ngx_http_wasm_module.c, src/http/ngx_http_wasm_util.c, src/wasm/ngx_wasm_util.c, t/03-proxy_wasm/006-on_http_next_action.t, t/03-proxy_wasm/hfuncs/102-proxy_send_local_response.t, t/lib/proxy-wasm-tests/hostcalls/src/tests/mod.rs, t/lib/proxy-wasm-tests/hostcalls/src/types/test_http.rs
Replaces #470 by implementing the feature at the Proxy-Wasm host layer.
=> feat(proxy-wasm) support 'send_local_response' during on_response_headers

src/common/ngx_wasm_socket_tcp.c, src/common/ngx_wasm_subsystem.c, src/common/ngx_wasm_subsystem.h, src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm.h, src/common/proxy_wasm/ngx_proxy_wasm_host.c, src/http/ngx_http_wasm.h, src/http/ngx_http_wasm_filter_module.c, src/http/ngx_http_wasm_module.c, src/http/proxy_wasm/ngx_http_proxy_wasm.c, src/http/proxy_wasm/ngx_http_proxy_wasm_dispatch.c, src/wasm/ngx_wasm.h, src/wasm/ngx_wasm_ops.c, t/03-proxy_wasm/hfuncs/102-proxy_send_local_response.t
Improvements to the proxy-wasm runloop extracted from eof flag work.
=> refactor(*) proxy-wasm runloop + req state enhancements

docs/PROXY_WASM.md, src/http/proxy_wasm/ngx_http_proxy_wasm.c, t/03-proxy_wasm/004-on_http_phases.t, t/03-proxy_wasm/hfuncs/115-proxy_get_http_response_body.t, t/lib/proxy-wasm-tests/on-phases/src/filter.rs
Reflect the fact that we do not know whether or not a request/response has a body in the RequestHeaders and ResponseHeaders steps due to internal Nginx behavior.
Thus, always pass `eof=false` to these handlers so filters can assume the same behavior: assuming that the request/response *may or may not* have a body. As such, both request/response body steps *may or may not* be invoked (same as Envoy), and the `eof` flag is not an appropriate heuristic for determining body steps invocations.
This also factorizes the on_http_phases suite into a much more concise set of tests.
See #504
=> fix(proxy-wasm) always pass 'eof=false' in header steps

src/common/shm/ngx_wasm_shm_kv.c
The first time `ngx_wasm_shm_kv_set_locked` is called with a key `k` and a value `v`, it allocates `sizeof(ngx_wasm_shm_kv_node_t) + key->len + value->len` bytes to store node, key and value contents.
If `ngx_wasm_shm_kv_set_locked` is later called with the key `k` and a value larger than `v`, it will write beyond the initially allocated memory when copying the value's bytes to the shared memory: `ngx_memcpy(n->value.data, value->data, value->len)`.
=> fix(shm/kv) re-allocate memory if current value is replaced by a larger one

t/03-proxy_wasm/hfuncs/132-proxy_dispatch_http_ssl.t
`ci-large` job has consistently [succeeded](https://github.com/Kong/ngx_wasm_module/actions/runs/8486803110) in the few times I've re-ran it.
=> chore(ci-large) increase tick_period in intermittently failing tests  

src/common/lua/ngx_wasm_lua_ffi.c, src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm.h, src/http/ngx_http_wasm.h, src/http/ngx_http_wasm_directives.c, src/http/ngx_http_wasm_module.c, src/http/ngx_http_wasm_util.c, src/http/ngx_http_wasm_util.h, src/wasm/ngx_wasm_ops.c, src/wasm/ngx_wasm_ops.h, t/04-openresty/ffi/101-proxy_wasm_load.t
Before instantiating filter chains and request contexts, filters themselves (i.e. their root context) are represented in the module. Eventually, `ngx_proxy_wasm_start` iterates over all filters to start their root contexts.
Previously, all filters declared in `proxy_wasm` directives were stored globally. With the introduction of the FFI filters can be dynamically added to the internal representation during `proxy_wasm.load`, which makes it possible for `ngx_proxy_wasm_start` to be invoked several times.
However, since the filters structure was global then all previously declared filters were started again, including filters that previously failed initializing their root contexts. This was not happening with `proxy_wasm` directives since a filter failing initialization in that case would …
=> fix(ffi) allow 'load()' to fail and be invoked again

docs/DIRECTIVES.md, src/http/ngx_http_wasm.h, src/http/ngx_http_wasm_module.c, src/wasm/ngx_wasm.h, src/wasm/ngx_wasm_core_module.c, src/wasm/ngx_wasm_util.c, t/02-http/004-postpone_rewrite.t, t/02-http/005-postpone_access.t, t/04-openresty/003-postpone_rewrite.t, t/04-openresty/004-postpone_access.t, t/04-openresty/ffi/302-proxy_wasm_properties_set_ngx.t, t/04-openresty/ffi/303-proxy_wasm_properties_set_host.t, t/TestWasmX.pm
Our module *must* run after the Lua module for the ongoing refactor of the Lua bridge. When the Lua module postpones its handlers, we postpone ours as well. This behavior assumes ngx_wasmx_module is declared after ngx_http_lua_module during compilation (static or dynamic). This could be enforced in the future in dynamic builds, and caught at runtime with a warning for static builds.
TODO
=> feat(http) implement 'postpone_rewrite' + 'postpone_access' directives

.github/workflows/job-unit-tests.yml, lib/ngx-wasm-rs/lib/wat/src/lib.rs
=> fix(lib) prevent a segfault loading an empty .wat module with V8

.github/workflows/ci-large.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml
=> chore(ci) move CodeQL analysis to its own recurring workflow

t/TestWasmX.pm, util/setup_dev.sh
The fix ensures that the `--- shutdown_error_log` check in the END block is skipped when no error.log was produced.
=> chore(util) apply a fix to Test::Nginx as a patch

src/common/proxy_wasm/ngx_proxy_wasm_maps.c, t/03-proxy_wasm/hfuncs/104-proxy_get_http_response_headers.t
Due to some Nginx internals (some response headers are added after our module is executed but before the response is sent) we inject "shim headers" into the `get_http_response_headers()` API. Some heuristics are used to determine whether or not `Transfer-Encoding`, `Connection`, or other "last minute" headers will be injected or not.
The issue is that the heuristics used are only valid during response production and after (e.g. `r->chunked` or
`r->headers_out.content_length_n` may only be relevant during and after response production). If a user uses `get_http_response_headers()` in request phases, the returned headers may include elements that will not actually be included in the response (e.g. `Transfer-Encoding`).
We now enforce that shim response headers should only be injected during …
=> fix(proxy-wasm) only inject shim headers after on_response_headers

src/common/lua/ngx_wasm_lua.c, src/common/lua/ngx_wasm_lua.h, src/common/lua/ngx_wasm_lua_resolver.c, src/common/ngx_wasm_socket_tcp.c, src/common/ngx_wasm_socket_tcp.h, src/wasm/ngx_wasm_core_host.c, t/04-openresty/lua-bridge/001-sanity.t, t/lib/ngx-lua-tests/src/lua_bridge.rs
An occasional memory leak of Proxy-Wasm dispatch with Lua bridge resolver, spotted by CI:
https://github.com/Kong/ngx_wasm_module/actions/runs/9884094484/job/27299927250
==19824== 224 bytes in 1 blocks are definitely lost in loss record 13 of 33
==19824==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==19824==    by 0x1E56AA: ngx_alloc (ngx_alloc.c:22)
==19824==    by 0x1CF926: ngx_resolver_alloc (ngx_resolver.c:4400)
==19824==    by 0x1CF926: ngx_resolver_calloc.isra.0 (ngx_resolver.c:4413)
==19824==    by 0x1D1EFD: ngx_resolve_start (ngx_resolver.c:661)
==19824==    by 0x392C80: ngx_wasm_socket_tcp_connect (ngx_wasm_socket_tcp.c:360)
==19824==    by 0x3BC984: ngx_http_proxy_wasm_dispatch_resume_handler (ngx_http_proxy_wasm_dispatch.c:745)
==19824== …
=> fix(*) resolve a potential memleak in Lua bridge resolver

src/common/proxy_wasm/ngx_proxy_wasm_host.c, src/common/proxy_wasm/ngx_proxy_wasm_util.c, t/03-proxy_wasm/003-on_tick.t, t/lib/proxy-wasm-tests/on-phases/src/filter.rs, t/lib/proxy-wasm-tests/on-tick/src/filter.rs
Passing `0` to `set_tick_period` signifies "cancel the tick".
=> feat(proxy-wasm) allow cancelling background ticks

src/http/ngx_http_wasm_local_response.c
This is to avoid mounting memory pressure as a longer-lived connection gets reused across many requests.
Before:
After:
(The initial peak in both graphs is the Cranelift compilation process.)
=> perf(http) stash local response in request pool

config, src/common/debug/ngx_wasm_debug_module.c, src/common/ngx_wa_readers.c, src/common/ngx_wa_readers.h, src/common/ngx_wasm_socket_tcp_readers.c, src/common/ngx_wasm_socket_tcp_readers.h
These will be used in IPC code.
=> refactor(*) generalize bytes readers for all ngx_wa

lib/resty/wasmx/shm.lua, t/04-openresty/ffi/shm/024-metrics_get_by_name.t
Previously, when parsing a histogram without uninitialized bins, `parse_cmetric` would incorrectly build an extra bin from invalid memory.
Histograms with uninitialized bins were correctly parsed due to `parse_cmetric` stop parsing bins when an uninitialized one is found.
=> fix(ffi) correct usage of 'n_bins' when parsing a histogram

src/ngx_wasmx.h, src/wasm/ngx_wasm.h, src/wasm/vm/ngx_wavm.c
=> refactor(*) generalize ngx_str_node_t and ngx_str_t extensions

docs/INSTALL.md, docs/README.md
We should ideally rename the module on GitHub and in the rest of the documentation. Since the archive name is ngx_wasmx_module, rename all mentions of it in INSTALL.md for now.
=> docs(install) rename module mentions as per the archive name

docs/DIRECTIVES.md, docs/PROXY_WASM.md, src/common/ngx_wasm_socket_tcp.c, src/common/ngx_wasm_socket_tcp.h, src/common/ngx_wasm_socket_tcp_readers.c, src/common/ngx_wasm_socket_tcp_readers.h, src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm_maps.c, src/http/ngx_http_wasm.h, src/http/ngx_http_wasm_module.c, src/http/proxy_wasm/ngx_http_proxy_wasm.c, src/http/proxy_wasm/ngx_http_proxy_wasm_dispatch.c, src/wasm/ngx_wasm.h, src/wasm/ngx_wasm_core_module.c, t/03-proxy_wasm/hfuncs/130-proxy_dispatch_http.t, t/03-proxy_wasm/hfuncs/131-proxy_dispatch_http_timeouts.t, t/03-proxy_wasm/hfuncs/132-proxy_dispatch_http_ssl.t, t/03-proxy_wasm/hfuncs/133-proxy_dispatch_http_edge_cases.t, t/03-proxy_wasm/sdks/002-go_sdk/005-dispatch_call_on_tick.t, t/lib/proxy-wasm-tests/hostcalls/src/filter.rs, t/lib/proxy-wasm-tests/hostcalls/src/lib.rs, util/sdks/go.sh
Invoke `on_http_call_response` on dispatch connection failures. This allows catching failures such as:
- timeout
- broken connection
- resolver failures
- TLS handshake failures
- Any other failures *after the connection has attempted to be established*
Dispatch failures occurring *before* a connection has attempted to be established will not trigger `on_http_call_response` as they are already supposed to trigger a Wasm exception (i.e. trap).
When a dispatch connection failure occurs, `on_http_call_response` is invoked with: `on_http_call_response(call_id, 0, 0, 0)` (i.e. no header, no body, no trailers). Calls to retrieve the response `:status` will return `None`. A user may triage the connection failure by querying the `:dispatch_status` pseudo-header:
```rust
fn on_http_call_response( …
```
=> feat(proxy-wasm) invoke 'on_http_call_response' on dispatch failures

t/03-proxy_wasm/hfuncs/130-proxy_dispatch_http.t, t/04-openresty/lua-bridge/002-proxy_wasm_lua_resolver_sanity.t, t/04-openresty/lua-bridge/003-proxy_wasm_lua_resolver_timeouts.t
We sometimes get a real 503 from httpbin.org as well. The tests still succeed in case of upstream errors.
=> tests(*) increase robustness of httpbin-reliant tests

lib/v8bridge/Makefile, util/runtimes/v8.sh
These need to be fixed in order to produce a bump to `ngx_wasm_runtimes`.
This puts us in an almost chicken-and-egg situation when bumping V8. We need to make a 3 (or rather 4) step process for bumping V8 if their build process changes:
1. make the tweaks in `ngx_wasm_module`
2. start an ARM VM and build the ARM binary image
3. bump in `ngx_wasm_runtimes`
4. bump the CI in `ngx_wasm_module`
This time I've done things out-of-order by tweaking the repo by hand in the ARM VM to get step 2 done first, but then I realized that step 3 won't work without step 1 (this PR). Another PR with step 4 will then follow.
(Perhaps the build part of `util/runtimes/v8.sh` should instead live in `ngx_wasm_runtimes`, so that all steps for building a new V8 artifact lived there, and then `ngx_wasm_module` …
=> chore(v8bridge) minor fixes for v8bridge build

src/wasm/vm/ngx_wavm.c
=> fix(wavm) use PRIu64 for printf portability across architectures

.github/workflows/job-unit-tests.yml, t/10-build/001-build_options.t
In our non-debug builds the `src/common/debug` exclude is unused and latest lcov complains about it.
=> chore(ci) ignore unused lcov exclusions

src/common/proxy_wasm/ngx_proxy_wasm_properties.c, t/03-proxy_wasm/hfuncs/117-proxy_properties_get.t, t/03-proxy_wasm/hfuncs/119-proxy_properties_get_ngx.t, t/03-proxy_wasm/hfuncs/120-proxy_properties_get_host.t, t/03-proxy_wasm/hfuncs/121-proxy_properties_set.t, t/03-proxy_wasm/hfuncs/122-proxy_properties_set_ngx.t, t/03-proxy_wasm/hfuncs/123-proxy_properties_set_host.t, t/04-openresty/ffi/300-proxy_wasm_properties_get_ngx.t, t/04-openresty/ffi/301-proxy_wasm_properties_get_host.t, t/04-openresty/ffi/302-proxy_wasm_properties_set_ngx.t, t/04-openresty/ffi/303-proxy_wasm_properties_set_host.t, t/04-openresty/lua-bridge/002-proxy_wasm_lua_resolver_sanity.t, t/lib/proxy-wasm-tests/hostcalls/src/lib.rs
Scoped properties (e.g. `request.*`, `response.*`, `upstream.*`, ...) can only be read/written from within the context of a request. Only non-scoped properties (e.g. `worker_id`) can be accessed from root contexts.
Prior to this commit, only `ngx.*` and `wasmx.*` (host) properties were caught. Other scoped properties that did not map to either of those would cause a segfault.
We now catch all scoped properties (i.e. containing a `.` character) when getting/setting properties outside of a request.
=> fix(proxy-wasm) catch get/set all scoped properties outside of requests

.github/workflows/ci-large.yml
Ubuntu 24.04 does not have clang-13 anymore.
=> chore(ci) bump clang builds to clang-14 + clang-18

docs/PROXY_WASM.md, src/common/proxy_wasm/ngx_proxy_wasm_properties.c, t/03-proxy_wasm/hfuncs/117-proxy_properties_get.t, t/lib/proxy-wasm-tests/hostcalls/src/filter.rs
Introduce a new request property `request.is_subrequest` to indicate whether the current request is a subrequest of an existing request (e.g. in slicing scenarios).
Note: Although the property uses the `request.*` prefix, this is not an Envoy attribute.
=> [MERGE] feat(proxy-wasm) new 'request.is_subrequest' property

src/common/proxy_wasm/ngx_proxy_wasm.c, src/common/proxy_wasm/ngx_proxy_wasm.h, src/common/proxy_wasm/ngx_proxy_wasm_properties.c, t/03-proxy_wasm/hfuncs/117-proxy_properties_get.t
No filter chain initialized on tick contexts means the root context must be stored in the empty filter chain context for later retrieval.
=> fix(proxy-wasm) support get 'plugin_name' in tick context

.github/workflows/release.yml
As per recent EOL warnings of `@v3`.
=> chore(release) bump upload/download artifacts GHA to @v4

src/wasm/ngx_wasm_ops.c, t/lib/proxy-wasm-tests/hostcalls/src/types/mod.rs
=> fix(ops) free plan struct on ngx_wasm_ops_plan_destroy

.github/workflows/release.yml
- Override `nightly` tag
- Remove previous nightly release artifacts
- Generate nightly release notes
=> chore(release) nightly release fixes
